services:
  - type: web
    name: health-techbuxin
    env: python
    pythonVersion: 3.11.9
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt && python migrate.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_y1uxES0jbqQl@ep-small-bar-adgjjs7g-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: CLOUDINARY_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: dlqutksgo
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: onboarding@resend.dev
      - key: ADMIN_EMAIL
        value: buxinhealth@gmail.com
      - key: ADMIN_PASSWORD
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "false"
